import { callLLM } from "@/utils/ai";
import { question, closeReadline } from "@/utils";
import { addDaily } from "@/commands/add/daily";
import type { Config } from "@/types";
import fs from "fs";
import path from "path";

export async function add(config: Config) {
  if (!config.settings.ai) {
    console.error("AI is not configured. Please run 'creanote ai setup' to configure AI settings.");
    process.exit(1);
  }

  const { llm } = config.settings.ai;
  
  const topic = await question("What topic would you like me to create a note about? ");

  if (!topic || topic.trim() === "") {
    console.error("No topic provided.");
    process.exit(1);
  }

  try {
    console.log("🤖 Generating note...");
    
    const systemPrompt = llm.prompt.add.system;
    const userPrompt = llm.prompt.add.user.replace("{topic}", topic);
    
    const aiContent = await callLLM(systemPrompt, userPrompt);
    
    // Create a daily note with AI content
    const today = new Date();
    const dateStr = today.toISOString().split('T')[0]; // YYYY-MM-DD format
    
    // Generate filename based on topic
    const sanitizedTopic = topic.toLowerCase()
      .replace(/[^a-z0-9\s]/g, '')
      .replace(/\s+/g, '-')
      .substring(0, 50);
    
    const filename = `${dateStr}-${sanitizedTopic}`;
    
    // Create the daily folder if it doesn't exist
    const dailyPath = config.settings.addPath.daily;
    if (!fs.existsSync(dailyPath)) {
      fs.mkdirSync(dailyPath, { recursive: true });
    }
    
    // Create the note file
    const notePath = path.join(dailyPath, `${filename}.md`);
    
    const noteContent = `# ${topic}

Generated on ${today.toLocaleDateString()} at ${today.toLocaleTimeString()}

${aiContent}

---
*This note was generated by AI using creanote*
`;
    
    fs.writeFileSync(notePath, noteContent);
    
    console.log(`✅ Note created: ${notePath}`);
    console.log(`📝 Topic: ${topic}`);
    console.log(`📅 Date: ${today.toLocaleDateString()}`);
    
  } catch (error) {
    console.error("Error:", error instanceof Error ? error.message : "Unknown error");
    process.exit(1);
  } finally {
    closeReadline();
  }
} 