# Adapted from create-turborepo, shadcn-ui/ui, create-t3-app.

name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  packages: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    if: ${{ github.repository_owner == 'elitalpa' }}
    name: Create a PR for release workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.6

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          version: 8.15.6
          node-version: 20
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm i

      - name: Build the package
        run: pnpm creanote:build

      - name: Create Version PR or Publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          commit: "chore(release): version packages"
          title: "chore(release): version packages"
          version: node .github/changeset-version.js
          publish: npx changeset publish
        env:
          # GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
          NPM_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          NODE_ENV: "production"
